server:
    port: 8081

spring:
    application:
        name: team-service
    datasource:
        url: jdbc:mysql://localhost:3306/ticdocs?serverTimezone=Asia/Shanghai&verifyServerCertificate=false&useSSL=false
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
    rabbitmq:
        port: 5672
        host: localhost
        stream:
            username: guest
            password: guest
            virtual-host: /
        publisher-confirm-type: correlated
        publisher-returns: true
        listener:
            simple:
                acknowledge-mode: manual
        template:
            mandatory: true

mybatis:
    mapper-locations: classpath:mybatis/*.xml
    type-aliases-package: com.doc.team.model
    configuration:
        map-underscore-to-camel-case: true